name: Update dependencies

on:
  pull_request:
    paths:
      - '.github/workflows/update-dependencies.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'  # "At 18:00 on Friday."

env:
  FORCE_COLOR: '1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  update-dependencies:
    name: Update dependencies
    permissions:
      contents: write  # needed to create new branch
      pull-requests: write  # needed to create PR for the new branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: "Install uv"
      run: pipx install uv
    - name: "Setup bot user"
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: "Run update native dependencies"
      run: |
        uv run --with jinja2 tools/update_native_dependencies.py
        uv run render.py
      env:
        GITHUB_API_TOKEN: ${{ github.token }}
    - name: Check changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git commit -am "[Bot] Update dependencies"
        fi
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main' && github.repository == 'rust-cross/manylinux-cross'
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        commit-message: Update python dependencies
        title: '[Bot] Update dependencies'
        body: |
          Update the versions of our dependencies.

          PR generated by "Update dependencies" [workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
        branch: update-dependencies-pr
        sign-commits: true
        token: ${{ github.token }}
        delete-branch: true